### ISSUE TITLE
DON'T ADD UNNECESSARY PAGES

### ISSUE THREAD

**Issue by Shaishav23** [mitee163/CIS634_FinalProject_TSM#12]
@kinjallpatel please don't add unnecessary pages. It is clashing with the current coding and is causing errors.
Thank you.

**Comment by kinjallpatel** [comment]
@Shaishav23 @mitee163 those are not unnecessary pages. Those are the pages what was asked for and I did something on my one too.
I was trying to solve the errors. But if it's clashing your code,then I will go ahead and delete it.

**Comment by Shaishav23** [comment]
Some pags that you created are already made like Logout and Create-Account functionality and other pages are not working with the current project, so please go ahead and delete it.
And If you want to add any other pages please make sure of the technology we are using.
Thank you.

**Comment by kinjallpatel** [comment]
As per conversation, Sign up page was required for both so I created one more. I did not saw logout page, so I added that too. And of course, it is of the same technology.

**Comment by mitee163** [comment]
Our sign up, login and logout functionalities are happening internally and they don't need separate create-account and logout pages right now. Thought you checked the existing application by running it at least, then it would have been clear or you could have asked us how all the technologies are working in the project, we are here to help.

And you needed to do the bills view page as per conversation and not signup or logout. Again should have at least asked us how to integrate the page in our application, it would have saved all our times.

No worries, we will work it out. Thank you!
